version: '2'

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: always
    env_file: .env 
    networks:
      - Inception_network
    volumes:
      - mariadb:/var/lib/mysql

  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
    - "443:443"
    networks:
      - Inception_network
    restart: always
    volumes:
      - wordpress:/var/www

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    restart: always
    env_file: .env
    networks:
      - Inception_network
    volumes:
      - wordpress:/var/www

volumes:
  wordpress:
    name: "wordrpess"
    driver: local
    driver_opts:
      type: none
      device: "/home/jduval/data/wordpress"
      o: bind
  mariadb:
    name: "mariadb"
    driver: local
    driver_opts:
      type: none
      device: "/home/jduval/data/mariadb"
      o: bind

networks:
  Inception_network:
    name: "Inception_network"
